spring.application.name=taller2_hotel
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/motel_db
spring.datasource.username=postgres
spring.datasource.password=PostgreS1367
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Evita el error de referencia circular al serializar
spring.jackson.serialization.fail-on-empty-beans=false